package registroclientes;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sposada
 */
public class VistaMenu extends javax.swing.JFrame {

    private Producto[] listaProductos;
    private ClientePremium[] misClientesPre;
    private Cliente miCliente; 
    private int tipoEnvio;
    private ArrayList <Compra> listaCompras;
    private double total;
    private DefaultTableModel miModelo;
    
    
        
    public VistaMenu() {
        initComponents();
        
           listaCompras = new ArrayList <>();
           
           listaProductos = new Producto[4];               
           listaProductos[0]= new Producto("Xiaomi Poco X3", 750000);               
           listaProductos[1] = new Producto("Motorola One Fusion", 560000);           
           listaProductos[2] = new Producto("Samsung Galaxy A21s",700000);  
           listaProductos[3] = new Producto("Portatil Asus M413da",2200000); 
           
            misClientesPre = new ClientePremium[4];      
            
            misClientesPre[0]= new ClientePremium("Juan","juan65", "C001", 1);               
            misClientesPre[1] = new ClientePremium("Maria","maria58", "C002", 2);             
            misClientesPre[2] = new ClientePremium("Jose","jose36", "C003", 2);   
            misClientesPre[3] = new ClientePremium("Diana","diana21", "C004", 1); 
        
            miCliente = null; 
            
            total = 0;
            tipoEnvio =1;

            cargarProductos();
            cargarTipoDeEnvio();
            cargarCompras();
            
            String[] columanas = {"CLIENTE", "PRODUCTO","CANTIDAD", "ENVIO" ,"DESCUENTO" , "TOTAL"};
            
            miModelo = new DefaultTableModel(columanas, 0);
            jTable.setModel(miModelo);
            
            
            
    }
    
    public void cargarProductos(){
        
        jCBproductos.removeAllItems();
        jCBproductos.addItem("Seleccione un producto");     
        
        for (Producto miProducto : listaProductos){        
        jCBproductos.addItem(miProducto.getDescripcion());        
        }
               
        
    }
    
    
     public void cargarTipoDeEnvio(){
                  
        jCBlugardeenvio.removeAllItems();
        jCBlugardeenvio.addItem("Local");
        jCBlugardeenvio.addItem("Nacional");
        jCBlugardeenvio.addItem("Internacional");
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTFnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFuser = new javax.swing.JTextField();
        jBvalidar = new javax.swing.JButton();
        jCBproductos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCBlugardeenvio = new javax.swing.JComboBox<>();
        jBagregarCompra = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScantidad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jRBnormal = new javax.swing.JRadioButton();
        jRBexpress = new javax.swing.JRadioButton();
        jLtotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Clientes Unab");

        jLabel2.setText("Nombre");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jTFnombre.setText("nombre");

        jLabel3.setText("User");

        jTFuser.setText("User");

        jBvalidar.setText("Validar");
        jBvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvalidarActionPerformed(evt);
            }
        });

        jCBproductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Producto");

        jLabel5.setText("Cantidad");

        jCBlugardeenvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBagregarCompra.setText("Agregar Ccompra");
        jBagregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarCompraActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Compra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Lugar de Envio");

        jLabel7.setText("Tipo de Envio");

        buttonGroup1.add(jRBnormal);
        jRBnormal.setText("Normal");
        jRBnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBnormalActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBexpress);
        jRBexpress.setText("Express");
        jRBexpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBexpressActionPerformed(evt);
            }
        });

        jLtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLtotal.setText("0.0");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("LISTA DE COMPRAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(211, 211, 211)
                        .addComponent(jLtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jTFuser, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBvalidar)
                            .addComponent(jLabel5)
                            .addComponent(jScantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(390, 390, 390))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBagregarCompra)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(391, 391, 391))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jCBproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBlugardeenvio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBexpress)
                            .addComponent(jRBnormal))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBvalidar))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCBproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBagregarCompra)
                            .addComponent(jButton3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLtotal)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBnormal)
                            .addComponent(jCBlugardeenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBexpress)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBnormalActionPerformed
        tipoEnvio = 2;        
    }//GEN-LAST:event_jRBnormalActionPerformed

    private void jBagregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarCompraActionPerformed
        
        Compra miCompra = new Compra();  
        
        int opc = jCBproductos.getSelectedIndex();
        int tipoLugar = jCBlugardeenvio.getSelectedIndex();        
        miCompra.tipoLugar = tipoLugar+1;
        miCompra.tipoEnvio = tipoEnvio;
        int bandera = 0;
        int cantidad = (int)jScantidad.getValue();
        miCompra.cantidad = cantidad;
        
        if (miCliente == null){
            miCliente = new Cliente();  
            miCliente.setNombre(jTFnombre.getText());
        }
        
        miCompra.cliente = miCliente;
        
        if (cantidad < 0){
            JOptionPane.showMessageDialog(this, "Fabricas de pendejos, se les escapo uno | cantidad debe ser posotivo");
        }        
        
        if(opc >0 && tipoEnvio > 0 && cantidad > 0){    
        miCompra.producto = listaProductos[opc-1];            
        bandera = 1;
        } else {
        JOptionPane.showMessageDialog(this, "debes rellenar todos los datos");       
        bandera=0;
        }
                            
        if (bandera==1){
        listaCompras.add(miCompra);
        cargarCompras();
        }
        
        
    }//GEN-LAST:event_jBagregarCompraActionPerformed

    private void cargarCompras(){
    
     String[] columnas = {"CLIENTE", "PRODUCTO","CANTIDAD", "ENVIO" ,"DESCUENTO" , "TOTAL"};
        miModelo = new DefaultTableModel(columnas, 0);        
        double total = 0;
        
        for (Compra laCompra : listaCompras) {
            miModelo.addRow(laCompra.getFila());
            total += laCompra.getTotal();
        }        
        
        jLtotal.setText("$"+String.format("%.1f", total));
        jTable.setModel(miModelo);    
        jCBproductos.setSelectedIndex(0);
    }
    
    
    private void jRBexpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBexpressActionPerformed
        tipoEnvio = 1;       
        
    }//GEN-LAST:event_jRBexpressActionPerformed

    private void jBvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvalidarActionPerformed
        
        String codigo = jTFuser.getText();
        miCliente = null;  
        
        for (ClientePremium miclientepre : misClientesPre) {                
            if ( (miclientepre.getCodigo()).equalsIgnoreCase(codigo)){
                miCliente = miclientepre;                                
                break;
            }  }
                           
            if (miCliente ==null){
               JOptionPane.showMessageDialog(this, "Codigo Invalido");  
               jTFnombre.setText("Invitado");
               jTFnombre.setEnabled(true);
            } else {
               JOptionPane.showMessageDialog(this, "Bienvenido :"+miCliente.getDescripcion());   
               jTFnombre.setText(miCliente.getNombre());
               jTFnombre.setEnabled(false);
               jScantidad.setValue(0);
            }
        
    }//GEN-LAST:event_jBvalidarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int select = jTable.getSelectedRow();
        
        if (select != -1 ){            
            listaCompras.remove(select);
            cargarCompras();
            
        } else {
            JOptionPane.showMessageDialog(this,  "Debes selecionar una fila");   
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBagregarCompra;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jBvalidar;
    private javax.swing.JComboBox<String> jCBlugardeenvio;
    private javax.swing.JComboBox<String> jCBproductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLtotal;
    private javax.swing.JRadioButton jRBexpress;
    private javax.swing.JRadioButton jRBnormal;
    private javax.swing.JSpinner jScantidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTextField jTFuser;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
